### ISSUE TITLE
Incorrect Product Price When Create Via Sales -> Orders

### ISSUE THREAD

**Issue by sylvainliang** [condor2/Opencart_2302#11]
Fresh installation with no extensions. Default demo data.

Steps to replicate.

1. Go to Sales -> Orders.
2. Click Add New button.
3. Customer Details tab. Choose a customer and click Continue button.
4. Products tab. Choose 'Sony VAIO'. 2 issues here.
- incorrect product price
- the product dropdown won't hide itself after choosing it or click elsewhere
![image](https://user-images.githubusercontent.com/45345195/105053721-3a110200-5aac-11eb-9015-0b1b699456dc.png)

Actual SONY VAIO price.
![image](https://user-images.githubusercontent.com/45345195/105053981-7a708000-5aac-11eb-8ead-1a1bce023d04.png)

5. Click Continue button.
6. Payment Details tab. Choose Address and click Continue button.
7. Shipping Details tab. Choose Address and click Continue button.
8. Totals tab. The price magically became correct here.
![image](https://user-images.githubusercontent.com/45345195/105054580-231edf80-5aad-11eb-9d1c-6fc00c8f733e.png)

9. Choose Shipping Method: Flat Shipping Rate - $5.00.
10. Choose Payment Method: Cash on Delivery.
11. Click Save button.
12. The final order is with correct pricing.
![image](https://user-images.githubusercontent.com/45345195/105055037-988ab000-5aad-11eb-8586-20b57393dd30.png)

**Comment by condor2** [comment]
I think depending by store settings...
![sony](https://user-images.githubusercontent.com/14251939/105150426-6c068080-5b0d-11eb-8535-1f858796133e.png)

**Comment by sylvainliang** [comment]
Could you please explain further what store settings? Because the amount doesn’t make sense to me.

**Comment by condor2** [comment]
If you have removed TAX from product, then set store to don't show TAX.

![no_tax](https://user-images.githubusercontent.com/14251939/105151343-81c87580-5b0e-11eb-8246-cb38c92f5c52.png)

**Comment by sylvainliang** [comment]
Perfect! Thank you.
