### ISSUE TITLE
Extension Sub Menu Intentionally Removed?

### ISSUE THREAD

**Issue by sylvainliang** [condor2/Opencart_2302#12]
Fresh installation of older (left image) and newer (right image) Condor2 versions. No extensions added and no changes in User Group. Newer version does not have submenu anymore. Is this intentional? Personally, I feel the submenu is really useful.
![image](https://user-images.githubusercontent.com/45345195/105684794-5f7c9080-5f30-11eb-946c-5e43d062849a.png)

**Comment by condor2** [comment]
Left image isn't from 2.3.0.2 version. It is from old version of opencart 2.0.x.x

**Comment by sylvainliang** [comment]
The page is too long so I'm not able to capture everything.
As you can see, there's submenu for extensions. There's also cron job, I guess you added this from master branch 3.1?
Footer copyright is V2.3.0.2.
![image](https://user-images.githubusercontent.com/45345195/105687042-ee8aa800-5f32-11eb-8a25-332737fa184f.png)

**Comment by condor2** [comment]
There is no submenu for Extensions in clean 2.3.0.2 version.....

**Comment by sylvainliang** [comment]
Ok, that's very strange then. I downloaded from here a copy of Commits on Sep 10, 2020. It has the submenu. I remember because it has the Cron Jobs. Since the submenu is gone now, then it's too bad. It's really nice to have it though.

**Comment by condor2** [comment]
My version never had a submenu for Extensions.

**Comment by condor2** [comment]
Edit this ocmod extension for your needs

https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=31470

**Comment by sylvainliang** [comment]
Thanks! Will try it out.

**Comment by condor2** [comment]
I will make a submenu for Extensions later.

**Comment by sylvainliang** [comment]
Sorry, you're right! Submenu was never in original or your 2.3.0.2 version. It is hidden and it can be fixed via https://forum.opencart.com/viewtopic.php?t=166071

**Comment by condor2** [comment]
https://www.opencart.com/index.php?route=marketplace/extension/info&extension_id=27812
