### ISSUE TITLE
Login to Admin Does Nothing

### ISSUE THREAD

**Issue by sylvainliang** [condor2/Opencart_2302#13]
I've installed latest copy "Commits on Jan 15, 2021". Fresh installation and deleted install folder.

Go to admin page to login. After key in username and password, then press Enter, it just appends token and does nothing.
![image](https://user-images.githubusercontent.com/45345195/105852466-751cb380-601f-11eb-89a8-3f7afda7ef81.png)

By right it should direct to admin dashboard, but it didn't.

Server environment:
Apache 2.4.46
PHP 7.3.26
MySQL 5.7.32-cll-lve

**Comment by condor2** [comment]
I have removed SameSite code
https://github.com/condor2/Opencart_2302/commit/10e558785a8375838d78e5f6e584d56e518259d5

Need more tests...

**Comment by sylvainliang** [comment]
I've applied the fix and it works now.
