### ISSUE TITLE
Image Manager

### ISSUE THREAD

**Issue by SoloApoellin** [condor2/Opencart_2302#3]
Clean Install. PHP version 7.3

Image manager not working

Also the same at 3.0.3.6

![screenshot](https://user-images.githubusercontent.com/20866439/95720738-4d752b80-0c7a-11eb-9c02-894386bcdbfd.png)

![screenshot-2](https://user-images.githubusercontent.com/20866439/95721005-a8a71e00-0c7a-11eb-8f08-162aec038698.png)

**Comment by condor2** [comment]
A temporary fix is to edit common.js and on **$element.popover({**, after **html: true,** add this line. 
`sanitize: false`

I will do some research hot to sanitize the code.
