### ISSUE TITLE
Resave Store Settings Fatal Errors

### ISSUE THREAD

**Issue by sylvainliang** [condor2/Opencart_2302#9]
When I tried to save store settings, whether I've changed it or not, I encounter errors below.

`Fatal error: Uncaught Exception: Error: <br />Error No: 0<br />INSERT INTO oc_setting SET store_id = '0', `code` = 'config', `key` = 'config_meta_title', `value` = 'Your Store' in C:\Apache24\htdocs\oc2cd\system\library\db\mysqli.php:46 Stack trace: #0 C:\Apache24\htdocs\oc2cd\system\library\db.php(45): DB\MySQLi->query('INSERT INTO oc_...') #1 C:\Apache24\htdocs\oc2cd\admin\model\setting\setting.php(25): DB->query('INSERT INTO oc_...') #2 C:\Apache24\htdocs\oc2cd\system\engine\loader.php(178): ModelSettingSetting->editSetting('config', Array) #3 C:\Apache24\htdocs\oc2cd\system\engine\proxy.php(25): Loader->{closure}(Array, Array) #4 C:\Apache24\htdocs\oc2cd\admin\controller\setting\setting.php(13): Proxy->__call('editSetting', Array) #5 C:\Apache24\htdocs\oc2cd\system\engine\action.php(51): ControllerSettingSetting->index() #6 C:\Apache24\htdocs\oc2cd\admin\controller\startup\router.php(29): Action->execute(Object(Registry), Array) #7 C:\Apache24\htdocs\oc2cd\system\engine\action.php(51): ControllerStartupRouter->index() in C:\Apache24\htdocs\oc2cd\system\library\db\mysqli.php on line 46`

And after the error, many text descriptions are not able to display. I screenshot only this but it happens in many places.
![text-description-error](https://user-images.githubusercontent.com/45345195/99161602-0b368280-272f-11eb-9c3e-6222515940e0.png)

**Comment by condor2** [comment]
Possible something weird with your localhost configuration.
Test on real hosting and see if you have same issue.

**Comment by sylvainliang** [comment]
I’ve tested on real hosting. Same issue. Another developer which I’ve requested to do extension customization encountered this error on real hosting as well.

**Comment by condor2** [comment]
Installation was a clean install? Or replaced with default 2.3.0.2?

**Comment by sylvainliang** [comment]
Clean installation.

**Comment by condor2** [comment]
Tested again and I don't have this issue.

Sure you don't have corrupted files or missing? Or issue with an extension?

**Comment by sylvainliang** [comment]
Two different persons tested on two different servers, clean installation and no extension installed and encounter these errors. I've downloaded a version on 16th September 2020 and it works. The current version which has new commits have all these fatal errors.

Your server have special setup and only works in that environment?

**Comment by condor2** [comment]
You use XAMPP for localhost?

**Comment by sylvainliang** [comment]
Nope, manual installation for Apache/2.4.43 (Win64), PHP/7.3.20 and mysqlnd 5.0.12-dev.

**Comment by condor2** [comment]
You have time to test on localhost with some new commits from octomber?

**Comment by sylvainliang** [comment]
I've downloaded on 16th September 2020: No errors (although some functions are not working for e.g. image manager, can't use search).
I've downloaded in November 2020: Encountered fatal errors. I believe this is the version that have new commits from October?

**Comment by condor2** [comment]
16 september or 20? I don't have commits on 16 september

**Comment by sylvainliang** [comment]
I downloaded on 16th September not because of your commits, but rather I decided to give it a try on that day. So this version have no errors. But when downloaded on November, it has fatal errors.

**Comment by condor2** [comment]
Ok.

So is something in commits after 10 september and latest.

Can you test my 3.0.3.6 on localhost and tell me if you have same issue?

**Comment by sylvainliang** [comment]
I've just tested 3.0.3.6 on localhost. None of the 4 errors I've reported occurred.

**Comment by condor2** [comment]
Tested on localhost using XAMPP and I can't reproduce the issues.

**Comment by sylvainliang** [comment]
`[Sun Nov 15 10:21:03.460364 2020] [php7:error] [pid 2832:tid 1036] [client ::1:49722] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />SELECT COUNT(*) AS total, date_added FROM `oc_order` WHERE order_status_id IN('5','3') AND DATE(date_added) >= '2020-11-1' GROUP BY DATE(date_added) in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('SELECT COUNT(*)...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\report\\sale.php(99): DB->query('SELECT COUNT(*)...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelReportSale->getTotalOrdersByMonth()\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\extension\\dashboard\\chart.php(179): Proxy->__call('getTotalOrdersB...', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerExtensionDashboardChart->chart()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=common/dashboard&token=c1fd812fa8ccaabe286dd8c0ee74c97b
[Sun Nov 15 10:23:57.288447 2020] [php7:error] [pid 2832:tid 1036] [client ::1:49787] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />INSERT INTO oc_setting SET store_id = '0', `code` = 'config', `key` = 'config_meta_title', `value` = 'Your Store1' in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('INSERT INTO oc_...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\setting\\setting.php(25): DB->query('INSERT INTO oc_...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelSettingSetting->editSetting('config', Array)\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\setting\\setting.php(13): Proxy->__call('editSetting', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerSettingSetting->index()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerStartupRouter->index( in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=setting/setting&token=c1fd812fa8ccaabe286dd8c0ee74c97b
[Sun Nov 15 10:28:22.803165 2020] [php7:error] [pid 2832:tid 1036] [client ::1:50204] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />SELECT COUNT(*) AS total, date_added FROM `oc_order` WHERE order_status_id IN() AND DATE(date_added) >= '2020-11-1' GROUP BY DATE(date_added) in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('SELECT COUNT(*)...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\report\\sale.php(99): DB->query('SELECT COUNT(*)...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelReportSale->getTotalOrdersByMonth()\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\extension\\dashboard\\chart.php(179): Proxy->__call('getTotalOrdersB...', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerExtensionDashboardChart->chart()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=common/dashboard&token=c1fd812fa8ccaabe286dd8c0ee74c97b
[Sun Nov 15 10:29:00.179742 2020] [php7:error] [pid 2832:tid 1052] [client ::1:50241] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />SELECT COUNT(*) AS total, date_added FROM `oc_order` WHERE order_status_id IN() AND DATE(date_added) >= '2020-11-1' GROUP BY DATE(date_added) in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('SELECT COUNT(*)...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\report\\sale.php(99): DB->query('SELECT COUNT(*)...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelReportSale->getTotalOrdersByMonth()\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\extension\\dashboard\\chart.php(179): Proxy->__call('getTotalOrdersB...', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerExtensionDashboardChart->chart()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=common/dashboard&token=f197ee3b1dede7acc24f61a735ad2831
[Sun Nov 15 10:35:12.297651 2020] [php7:error] [pid 2832:tid 1052] [client ::1:50462] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />SELECT * FROM `oc_store` WHERE REPLACE(`url`, 'www.', '') = 'http://localhost/oc2cd/' in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('SELECT * FROM `...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\catalog\\controller\\startup\\startup.php(5): DB->query('SELECT * FROM `...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerStartupStartup->index()\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\front.php(34): Action->execute(Object(Registry))\n#4 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\front.php(19): Front->execute(Object(Action))\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\framework.php(116): Front->dispatch(Object(Action), Object(Action))\n#6 C:\\Apache24\\htdocs\\oc2cd\\system\\startup.php(124): require_once('C:\\\\Apache24\\\\htd...')\n#7 C:\\Apache24\\htdocs\\oc2cd\\index.php(19): start('catalog')\n#8 {main}\n  thrown in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46
[Sun Nov 15 10:36:19.236248 2020] [php7:error] [pid 2832:tid 1048] [client ::1:50479] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />SELECT COUNT(*) AS total, date_added FROM `oc_order` WHERE order_status_id IN('5','3') AND DATE(date_added) >= '2020-11-1' GROUP BY DATE(date_added) in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('SELECT COUNT(*)...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\report\\sale.php(99): DB->query('SELECT COUNT(*)...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelReportSale->getTotalOrdersByMonth()\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\extension\\dashboard\\chart.php(179): Proxy->__call('getTotalOrdersB...', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerExtensionDashboardChart->chart()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=common/dashboard&token=b667091531bd64ded08c5dd0492ea466
[Sun Nov 15 10:36:55.603842 2020] [php7:error] [pid 2832:tid 1052] [client ::1:50551] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />INSERT INTO `oc_product_option` SET `product_option_id` = '223', `product_id` = '42', `option_id` = '2', `required` = '1' in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('INSERT INTO `oc...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\catalog\\product.php(236): DB->query('INSERT INTO `oc...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelCatalogProduct->editProduct('42', Array)\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\catalog\\product.php(75): Proxy->__call('editProduct', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerCatalogProduct->edit()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerStartupRouter->ind in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=catalog/product/edit&token=b667091531bd64ded08c5dd0492ea466&product_id=42
[Sun Nov 15 10:38:10.491908 2020] [php7:error] [pid 2832:tid 1048] [client ::1:50596] PHP Fatal error:  Uncaught Exception: Error: <br />Error No: 0<br />INSERT INTO oc_setting SET store_id = '0', `code` = 'config', `key` = 'config_meta_title', `value` = 'Your Store' in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php:46\nStack trace:\n#0 C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db.php(45): DB\\MySQLi->query('INSERT INTO oc_...')\n#1 C:\\Apache24\\htdocs\\oc2cd\\admin\\model\\setting\\setting.php(25): DB->query('INSERT INTO oc_...')\n#2 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\loader.php(178): ModelSettingSetting->editSetting('config', Array)\n#3 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\proxy.php(25): Loader->{closure}(Array, Array)\n#4 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\setting\\setting.php(13): Proxy->__call('editSetting', Array)\n#5 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerSettingSetting->index()\n#6 C:\\Apache24\\htdocs\\oc2cd\\admin\\controller\\startup\\router.php(29): Action->execute(Object(Registry), Array)\n#7 C:\\Apache24\\htdocs\\oc2cd\\system\\engine\\action.php(51): ControllerStartupRouter->index() in C:\\Apache24\\htdocs\\oc2cd\\system\\library\\db\\mysqli.php on line 46, referer: http://localhost/oc2cd/admin/index.php?route=setting/setting&token=b667091531bd64ded08c5dd0492ea466`

Maybe you want to test on real hosting instead?

**Comment by condor2** [comment]
As I said no issue on real hosting...
XAMPP was installed today...to see if I have these errors...

**Comment by sylvainliang** [comment]
I just re-download and tried on real hosting again. Still the same issues. I hope other people can give it a try as well and provide the results.

**Comment by condor2** [comment]
Can you test version from 10 octomber?
https://github.com/condor2/Opencart_2302/tree/bce0e195cac884ea37ccc2aaf5850710fcda5b8a

**Comment by sylvainliang** [comment]
I've tested this version https://github.com/condor2/Opencart_2302/tree/bce0e195cac884ea37ccc2aaf5850710fcda5b8a in real hosting. I did not perform this though https://github.com/condor2/Opencart_2302/blob/master/README.md.

All the 4 errors I've reported did not occur anymore. May I know what's the difference for this version and master branch https://github.com/condor2/Opencart_2302/archive/master.zip?

**Comment by condor2** [comment]
Download again Master, update new config and test.
In master I added some changes from Master Branch 3.1.xx

**Comment by sylvainliang** [comment]
I've done fresh installation of master. Still the same errors.

**Comment by condor2** [comment]
Replace current mysqli code with this one
https://github.com/condor2/Opencart_2302/blob/0b2d4e3db545a3b7a5e3d47da7830f7b0791d2cf/upload/system/library/db/mysqli.php

And tell me if have same errors

**Comment by sylvainliang** [comment]
Excellent! It works now! So this file is the only culprit that caused all these errors?

**Comment by condor2** [comment]
I will restore later.
